export const NEWS_SOURCES = {
    'abc-news-au': 'ABC News (AU)',
    'al-jazeera-english': 'Al Jazeera English',
    'ars-technica': 'Ars Technica',
    'associated-press': 'Associated Press',
    'bbc-news': 'BBC News',
    'bbc-sport': 'BBC Sport',
    'bild': 'Bild',
    'bloomberg': 'Bloomberg',
    'breitbart-news': 'Breitbart News',
    'business-insider': 'Business Insider',
    'business-insider-uk': 'Business Insider (UK)',
    'buzzfeed': 'Buzzfeed',
    'cnbc': 'CNBC',
    'cnn': 'CNN',
    'daily-mail': 'Daily Mail',
    'der-tagesspiegel': 'Der Tagesspiegel',
    'die-zeit': 'Die Zeit',
    'engadget': 'Engadget',
    'entertainment-weekly': 'Entertainment Weekly',
    'espn': 'ESPN',
    'espn-cric-info': 'ESPN Cric Info',
    'financial-times': 'Financial Times',
    'focus': 'Focus',
    'football-italia': 'Football Italia',
    'fortune': 'Fortune',
    'four-four-two': 'FourFourTwo',
    'fox-sports': 'Fox Sports',
    'google-news': 'Google News',
    'gruenderszene': 'Gruenderszene',
    'hacker-news': 'Hacker News',
    'handelsblatt': 'Handelsblatt',
    'ign': 'IGN',
    'independent': 'Independent',
    'mashable': 'Mashable',
    'metro': 'Metro',
    'mirror': 'Mirror',
    'mtv-news': 'MTV News',
    'mtv-news-uk': 'MTV News (UK)',
    'national-geographic': 'National Geographic',
    'new-scientist': 'New Scientist',
    'newsweek': 'Newsweek',
    'new-york-magazine': 'New York Magazine',
    'nfl-news': 'NFL News',
    'polygon': 'Polygon',
    'recode': 'Recode',
    'reddit-r-all': 'Reddit /r/all',
    'reuters': 'Reuters',
    'spiegel-online': 'Spiegel Online',
    't3n': 'T3n',
    'talksport': 'TalkSport',
    'techcrunch': 'TechCrunch',
    'techradar': 'TechRadar',
    'the-economist': 'The Economist',
    'the-guardian-au': 'The Guardian (AU)',
    'the-guardian-uk': 'The Guardian (UK)',
    'the-hindu': 'The Hindu',
    'the-huffington-post': 'The Huffington Post',
    'the-lad-bible': 'The Lad Bible',
    'the-new-york-times': 'The New York Times',
    'the-next-web': 'The Next Web',
    'the-sport-bible': 'The Sport Bible',
    'the-telegraph': 'The Telegraph',
    'the-times-of-india': 'The Times of India',
    'the-verge': 'The Verge',
    'the-wall-street-journal': 'The Wall Street Journal',
    'the-washington-post': 'The Washington Post',
    'time': 'Time',
    'usa-today': 'USA Today',
    'wired-de': 'Wired.de',
    'wirtschafts-woche': 'Wirtschafts Woche'
}