module.exports = {
    NEWS_SOURCES: {
        'abc-news-au': 'ABC News (AU)',
        'associated-press': 'Associated Press',
        'bbc-news': 'BBC News',
        'bbc-sport': 'BBC Sport',
        'bloomberg': 'Bloomberg',
        'business-insider': 'Business Insider',
        'business-insider-uk': 'Business Insider (UK)',
        'buzzfeed': 'Buzzfeed',
        'cnbc': 'CNBC',
        'cnn': 'CNN',
        'daily-mail': 'Daily Mail',
        'engadget': 'Engadget',
        'entertainment-weekly': 'Entertainment Weekly',
        'espn': 'ESPN',
        'financial-times': 'Financial Times',
        'fortune': 'Fortune',
        'fox-sports': 'Fox Sports',
        'google-news': 'Google News',
        'hacker-news': 'Hacker News',
        'ign': 'IGN',
        'independent': 'Independent',
        'metro': 'Metro',
        'mirror': 'Mirror',
        'mtv-news': 'MTV News',
        'national-geographic': 'National Geographic',
        'new-scientist': 'New Scientist',
        'new-york-magazine': 'New York Magazine',
        'polygon': 'Polygon',
        'recode': 'Recode',
        'reddit-r-all': 'Reddit /r/all',
        'reuters': 'Reuters',
        'talksport': 'TalkSport',
        'techcrunch': 'TechCrunch',
        'techradar': 'TechRadar',
        'the-economist': 'The Economist',
        'the-guardian-au': 'The Guardian (AU)',
        'the-guardian-uk': 'The Guardian (UK)',
        'the-hindu': 'The Hindu',
        'the-new-york-times': 'The New York Times',
        'the-sport-bible': 'The Sport Bible',
        'the-telegraph': 'The Telegraph',
        'the-times-of-india': 'The Times of India',
        'the-verge': 'The Verge',
        'the-wall-street-journal': 'The Wall Street Journal',
        'the-washington-post': 'The Washington Post',
        'time': 'Time',
        'usa-today': 'USA Today'
    },
    TEST_NEWS_SOURCES: {
        // 'bbc-news': 'BBC News',
        // 'bloomberg': 'Bloomberg',
        // 'techcrunch': 'TechCrunch',
        // 'cnn': 'CNN',
        // 'engadget': 'Engadget',
        // 'financial-times': 'Financial Times',
        // 'ign': 'IGN',
        // 'the-wall-street-journal': 'The Wall Street Journal',
        // 'reuters': 'Reuters',
        // 'bbc-sport': 'BBC Sport',
        // 'the-economist': 'The Economist',
        // 'the-guardian-uk': 'The Guardian (UK)',
        // 'business-insider': 'Business Insider',
        'fortune': 'Fortune',
        'fox-sports': 'Fox Sports',
        'google-news': 'Google News',
        'cnn': 'CNN',
        'national-geographic': 'National Geographic',
        'new-scientist': 'New Scientist',
        'usa-today': 'USA Today',
        'the-washington-post': 'The Washington Post',
        'the-new-york-times': 'The New York Times',
        'the-sport-bible': 'The Sport Bible',
        'the-telegraph': 'The Telegraph',
        'independent': 'Independent',
    },

    NEWS_API_URL: 'https://newsapi.org/v1/articles',
    NEWS_API_KEY: '58c39a23cd4e4dcb824927c34f075bf1',

    NLP_API_URL: 'http://api.textrazor.com',
    NLP_API_KEY: 'b82cc0700af44c0ac1995f20a639ae86fcd5c967964c083f11f1cde2',

    FIREBASE_URL: 'https://news-explorer-b987d.firebaseio.com/'
}