export default {
    'ABC News (AU)': 'https://icons.better-idea.org/icon?url=http://www.abc.net.au/news&amp;size=70..120..200',
    'Al Jazeera English': 'https://icons.better-idea.org/icon?url=http://www.aljazeera.com&amp;size=70..120..200',
    'Ars Technica': 'https://icons.better-idea.org/icon?url=http://arstechnica.com&amp;size=70..120..200',
    'Associated Press': 'https://icons.better-idea.org/icon?url=https://apnews.com/&amp;size=70..120..200',
    'BBC News': 'https://icons.better-idea.org/icon?url=http://www.bbc.co.uk/news&amp;size=70..120..200',
    'BBC Sport': 'https://icons.better-idea.org/icon?url=http://www.bbc.co.uk/sport&amp;size=70..120..200',
    'Bild': 'https://icons.better-idea.org/icon?url=http://www.bild.de&amp;size=70..120..200',
    'Bloomberg': 'https://icons.better-idea.org/icon?url=http://www.bloomberg.com&amp;size=70..120..200',
    'Breitbart News': 'https://icons.better-idea.org/icon?url=http://www.breitbart.com&amp;size=70..120..200',
    'Business Insider': 'https://icons.better-idea.org/icon?url=http://www.businessinsider.com&amp;size=70..120..200',
    'Business Insider (UK)': 'https://icons.better-idea.org/icon?url=http://uk.businessinsider.com&amp;size=70..120..200',
    'Buzzfeed': 'https://icons.better-idea.org/icon?url=https://www.buzzfeed.com&amp;size=70..120..200',
    'CNBC': 'https://icons.better-idea.org/icon?url=http://www.cnbc.com&amp;size=70..120..200',
    'CNN': 'https://icons.better-idea.org/icon?url=http://us.cnn.com&amp;size=70..120..200',
    'Daily Mail': 'https://icons.better-idea.org/icon?url=http://www.dailymail.co.uk/home/index.html&amp;size=70..120..200',
    'Der Tagesspiegel': 'https://icons.better-idea.org/icon?url=http://www.tagesspiegel.de&amp;size=70..120..200',
    'Die Zeit': 'https://icons.better-idea.org/icon?url=http://www.zeit.de/index&amp;size=70..120..200',
    'Engadget': 'https://icons.better-idea.org/icon?url=https://www.engadget.com&amp;size=70..120..200',
    'Entertainment Weekly': 'https://icons.better-idea.org/icon?url=http://www.ew.com&amp;size=70..120..200',
    'ESPN': 'https://icons.better-idea.org/icon?url=http://espn.go.com&amp;size=70..120..200',
    'ESPN Cric Info': 'https://icons.better-idea.org/icon?url=http://www.espncricinfo.com/&amp;size=70..120..200',
    'Financial Times': 'https://icons.better-idea.org/icon?url=http://www.ft.com/home/uk&amp;size=70..120..200',
    'Focus': 'https://icons.better-idea.org/icon?url=http://www.focus.de&amp;size=70..120..200',
    'Football Italia': 'https://icons.better-idea.org/icon?url=http://www.football-italia.net&amp;size=70..120..200',
    'Fortune': 'https://icons.better-idea.org/icon?url=http://fortune.com&amp;size=70..120..200',
    'FourFourTwo': 'https://icons.better-idea.org/icon?url=http://www.fourfourtwo.com/news&amp;size=70..120..200',
    'Fox Sports': 'https://icons.better-idea.org/icon?url=http://www.foxsports.com&amp;size=70..120..200',
    'Google News': 'https://icons.better-idea.org/icon?url=https://news.google.com&amp;size=70..120..200',
    'Gruenderszene': 'https://icons.better-idea.org/icon?url=http://www.gruenderszene.de&amp;size=70..120..200',
    'Hacker News': 'https://icons.better-idea.org/icon?url=https://news.ycombinator.com&amp;size=70..120..200',
    'Handelsblatt': 'https://icons.better-idea.org/icon?url=http://www.handelsblatt.com&amp;size=70..120..200',
    'IGN': 'https://icons.better-idea.org/icon?url=http://www.ign.com&amp;size=70..120..200',
    'Independent': 'https://icons.better-idea.org/icon?url=http://www.independent.co.uk&amp;size=70..120..200',
    'Mashable': 'https://icons.better-idea.org/icon?url=http://mashable.com&amp;size=70..120..200',
    'Metro': 'https://icons.better-idea.org/icon?url=http://metro.co.uk&amp;size=70..120..200',
    'Mirror': 'https://icons.better-idea.org/icon?url=http://www.mirror.co.uk/&amp;size=70..120..200',
    'MTV News': 'https://icons.better-idea.org/icon?url=http://www.mtv.com/news&amp;size=70..120..200',
    'MTV News (UK)': 'https://icons.better-idea.org/icon?url=http://www.mtv.co.uk/news&amp;size=70..120..200',
    'National Geographic': 'https://icons.better-idea.org/icon?url=http://news.nationalgeographic.com&amp;size=70..120..200',
    'New Scientist': 'https://icons.better-idea.org/icon?url=https://www.newscientist.com/section/news&amp;size=70..120..200',
    'Newsweek': 'https://icons.better-idea.org/icon?url=http://www.newsweek.com&amp;size=70..120..200',
    'New York Magazine': 'https://icons.better-idea.org/icon?url=http://nymag.com&amp;size=70..120..200',
    'NFL News': 'https://icons.better-idea.org/icon?url=http://www.nfl.com/news&amp;size=70..120..200',
    'Polygon': 'https://icons.better-idea.org/icon?url=http://www.polygon.com&amp;size=70..120..200',
    'Recode': 'https://icons.better-idea.org/icon?url=http://www.recode.net&amp;size=70..120..200',
    'Reddit /r/all': 'https://icons.better-idea.org/icon?url=https://www.reddit.com/r/all&amp;size=70..120..200',
    'Reuters': 'https://icons.better-idea.org/icon?url=http://www.reuters.com&amp;size=70..120..200',
    'Spiegel Online': 'https://icons.better-idea.org/icon?url=http://www.spiegel.de&amp;size=70..120..200',
    'T3n': 'https://icons.better-idea.org/icon?url=http://t3n.de&amp;size=70..120..200',
    'TalkSport': 'https://icons.better-idea.org/icon?url=http://talksport.com&amp;size=70..120..200',
    'TechCrunch': 'https://icons.better-idea.org/icon?url=https://techcrunch.com&amp;size=70..120..200',
    'TechRadar': 'https://icons.better-idea.org/icon?url=http://www.techradar.com&amp;size=70..120..200',
    'The Economist': 'https://icons.better-idea.org/icon?url=http://www.economist.com&amp;size=70..120..200',
    'The Guardian (AU)': 'https://icons.better-idea.org/icon?url=https://www.theguardian.com/au&amp;size=70..120..200',
    'The Guardian (UK)': 'https://icons.better-idea.org/icon?url=https://www.theguardian.com/uk&amp;size=70..120..200',
    'The Hindu': 'https://icons.better-idea.org/icon?url=http://www.thehindu.com&amp;size=70..120..200',
    'The Huffington Post': 'https://icons.better-idea.org/icon?url=http://www.huffingtonpost.com&amp;size=70..120..200',
    'The Lad Bible': 'https://icons.better-idea.org/icon?url=http://www.theladbible.com&amp;size=70..120..200',
    'The New York Times': 'https://icons.better-idea.org/icon?url=http://www.nytimes.com&amp;size=70..120..200',
    'The Next Web': 'https://icons.better-idea.org/icon?url=http://thenextweb.com&amp;size=70..120..200',
    'The Sport Bible': 'https://icons.better-idea.org/icon?url=http://www.thesportbible.com&amp;size=70..120..200',
    'The Telegraph': 'https://icons.better-idea.org/icon?url=http://www.telegraph.co.uk&amp;size=70..120..200',
    'The Times of India': 'https://icons.better-idea.org/icon?url=http://timesofindia.indiatimes.com&amp;size=70..120..200',
    'The Verge': 'https://icons.better-idea.org/icon?url=http://www.theverge.com&amp;size=70..120..200',
    'The Wall Street Journal': 'https://icons.better-idea.org/icon?url=http://www.wsj.com&amp;size=70..120..200',
    'The Washington Post': 'https://icons.better-idea.org/icon?url=https://www.washingtonpost.com&amp;size=70..120..200',
    'Time': 'https://icons.better-idea.org/icon?url=http://time.com&amp;size=70..120..200',
    'USA Today': 'https://icons.better-idea.org/icon?url=http://www.usatoday.com/news&amp;size=70..120..200',
    'Wired.de': 'https://icons.better-idea.org/icon?url=https://www.wired.de&amp;size=70..120..200',
    'Wirtschafts Woche': 'https://icons.better-idea.org/icon?url=http://www.wiwo.de&amp;size=70..120..200',
};